### ISSUE TITLE
testsuite failed to build with ghc-9.10.1

### ISSUE THREAD

**Issue by juhp** [rudymatela/conjure#4]
For Stackage Nightly:
```
       Building test suite 'derive' for code-conjure-0.5.14...
       [1 of 3] Compiling Test.ListableExpr            
       [2 of 3] Compiling Test                                    
       [3 of 3] Compiling Main                                    
       /home/curators/work/unpack-dir/unpacked/code-conjure-0.5.14-963ecadbaf2e47fd02dc71bc17ed7fde9fb75ad95814057e42b5220fd3cb8569/
test/derive.hs:14:22: error: [GHC-87543]  
           Ambiguous occurrence ‘List’. 
           It could refer to                                      
              either ‘Test.List’,                                 
                     imported from ‘Test’ at test/derive.hs:9:1-32
                     (and originally defined in ‘ghc-prim-0.11.0:GHC.Types’),                                                       
                  or ‘Main.List’, defined at test/derive.hs:14:1.
          |                                                       
       14 | data List a  =  a :- List a | Nil deriving (Show, Eq, Typeable)                                                         
          |                      ^^^^
```

**Comment by rudymatela** [comment]
@juhp Thanks for reporting.

This is fixed on code-conjure 0.5.16 released earlier today.
